version: '3.7'

services:
  db:
    image: postgres:latest
    container_name: next-postgres
    environment:
      POSTGRES_DB: establishments
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: est12TYu89!
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: next-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - db
